// Seed data for demo purposes
export const seedMockData = () => {
  // Check if data already exists
  const existingListings = localStorage.getItem('propertyListings');
  if (existingListings && JSON.parse(existingListings).length > 0) {
    return; // Don't overwrite existing data
  }

  const mockListings = [
    {
      id: 'mock-1',
      category: 'pg',
      title: 'Comfortable Single Room PG in Koregaon Park',
      description: 'Fully furnished single room PG with all modern amenities. Perfect for working professionals. Located in the heart of Koregaon Park with easy access to offices and shopping areas.',
      propertyType: 'Single Room',
      area: 'Koregaon Park',
      address: 'Lane 5, North Main Road',
      price: 12000,
      amenities: ['WiFi', 'TV', 'AC', 'Fridge', 'Water'],
      lift: true,
      waterType: 'ro',
      ownerId: 'demo-owner-1',
      ownerName: 'Rahul Sharma',
      ownerEmail: 'rahul.sharma@example.com',
      ownerPhone: '9876543210',
      status: 'approved',
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-2',
      category: 'pg',
      title: 'Double Sharing PG Near Hinjewadi IT Park',
      description: 'Spacious double sharing accommodation with homely food and Wi-Fi. Just 10 minutes from Hinjewadi Phase 2.',
      propertyType: 'Double Sharing',
      area: 'Hinjewadi',
      address: 'Phase 2, Rajiv Gandhi IT Park Road',
      price: 8000,
      amenities: ['WiFi', 'TV', 'Fridge', 'Water'],
      lift: true,
      waterType: 'ro',
      ownerId: 'demo-owner-2',
      ownerName: 'Priya Patil',
      ownerEmail: 'priya.patil@example.com',
      ownerPhone: '9876543211',
      status: 'approved',
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-3',
      category: 'rent',
      title: 'Spacious 2BHK Apartment in Baner',
      description: 'Beautiful 2BHK flat with modern amenities, covered parking, and 24/7 security. Family-friendly society with park and gym.',
      propertyType: 'Apartment',
      area: 'Baner',
      address: 'Kumar Paradise, Baner Road',
      price: 25000,
      bedrooms: 2,
      bathrooms: 2,
      amenities: ['WiFi', 'AC', 'Water'],
      lift: true,
      waterType: 'both',
      ownerId: 'demo-owner-3',
      ownerName: 'Amit Kumar',
      ownerEmail: 'amit.kumar@example.com',
      ownerPhone: '9876543212',
      status: 'approved',
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-4',
      category: 'rent',
      title: 'Luxury 3BHK House in Aundh',
      description: 'Premium 3BHK independent house with private parking, garden, and terrace. Ideal for families looking for peaceful living.',
      propertyType: 'House',
      area: 'Aundh',
      address: 'Aundh Gaon, ITI Road',
      price: 45000,
      bedrooms: 3,
      bathrooms: 3,
      amenities: ['WiFi', 'TV', 'AC', 'Fridge', 'Water'],
      lift: false,
      waterType: 'ro',
      ownerId: 'demo-owner-4',
      ownerName: 'Sneha Desai',
      ownerEmail: 'sneha.desai@example.com',
      ownerPhone: '9876543213',
      status: 'approved',
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-5',
      category: 'sell',
      title: 'Modern 3BHK Apartment for Sale in Kharadi',
      description: 'Brand new 3BHK apartment with all modern amenities. Ready to move in. Great investment opportunity in rapidly developing area.',
      propertyType: 'Apartment',
      area: 'Kharadi',
      address: 'Eon Free Zone, Kharadi',
      price: 8500000,
      bedrooms: 3,
      bathrooms: 2,
      amenities: ['WiFi', 'AC', 'Water'],
      lift: true,
      waterType: 'ro',
      ownerId: 'demo-owner-5',
      ownerName: 'Vikram Singh',
      ownerEmail: 'vikram.singh@example.com',
      ownerPhone: '9876543214',
      status: 'approved',
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-6',
      category: 'sell',
      title: 'Premium Villa in Wakad',
      description: 'Luxurious 4BHK villa with private garden, swimming pool access, and club house. Perfect for large families.',
      propertyType: 'Villa',
      area: 'Wakad',
      address: 'Dange Chowk, Wakad',
      price: 15000000,
      bedrooms: 4,
      bathrooms: 4,
      amenities: ['WiFi', 'TV', 'AC', 'Fridge', 'Water'],
      lift: false,
      waterType: 'both',
      ownerId: 'demo-owner-6',
      ownerName: 'Anjali Mehta',
      ownerEmail: 'anjali.mehta@example.com',
      ownerPhone: '9876543215',
      status: 'approved',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-7',
      category: 'pg',
      title: 'Triple Sharing PG in Viman Nagar',
      description: 'Affordable triple sharing PG with homemade food included. Close to Phoenix Mall and IT companies.',
      propertyType: 'Triple Sharing',
      area: 'Viman Nagar',
      address: 'Near Airport Road',
      price: 6500,
      amenities: ['WiFi', 'Water'],
      lift: false,
      waterType: 'tap',
      ownerId: 'demo-owner-7',
      ownerName: 'Suresh Pawar',
      ownerEmail: 'suresh.pawar@example.com',
      ownerPhone: '9876543216',
      status: 'approved',
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-8',
      category: 'rent',
      title: '1BHK Flat in Kothrud',
      description: 'Cozy 1BHK apartment perfect for bachelors or small families. Well connected to Karve Road and Law College Road.',
      propertyType: 'Apartment',
      area: 'Kothrud',
      address: 'Mayur Colony, Kothrud',
      price: 15000,
      bedrooms: 1,
      bathrooms: 1,
      amenities: ['WiFi', 'Water'],
      lift: true,
      waterType: 'tap',
      ownerId: 'demo-owner-8',
      ownerName: 'Deepak Joshi',
      ownerEmail: 'deepak.joshi@example.com',
      ownerPhone: '9876543217',
      status: 'approved',
      createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop'
    }
  ];

  localStorage.setItem('propertyListings', JSON.stringify(mockListings));
  console.log('Mock data seeded successfully!');
  
  // Seed flatmate profiles
  const existingFlatmates = localStorage.getItem('flatmateProfiles');
  if (existingFlatmates && JSON.parse(existingFlatmates).length > 0) {
    return; // Don't overwrite existing flatmate data
  }
  
  const mockFlatmates = [
    {
      id: 'flatmate-1',
      name: 'Rohan Mehta',
      age: 26,
      gender: 'male',
      occupation: 'Software Engineer',
      preferredArea: 'Hinjewadi',
      budget: 10000,
      hasPlace: false,
      lookingFor: 'male',
      vegetarian: true,
      smoking: false,
      drinking: false,
      petFriendly: false,
      description: 'Working professional at a tech company. Looking for a clean, quiet flatmate who values personal space. I enjoy reading, coding, and occasional outdoor activities. Non-smoker and vegetarian. Prefer someone with similar lifestyle.',
      phone: '9876543220',
      userId: 'demo-flatmate-user-1',
      userEmail: 'rohan.mehta@example.com',
      status: 'approved',
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      id: 'flatmate-2',
      name: 'Priya Sharma',
      age: 24,
      gender: 'female',
      occupation: 'Marketing Manager',
      preferredArea: 'Koregaon Park',
      budget: 15000,
      hasPlace: true,
      lookingFor: 'female',
      vegetarian: true,
      smoking: false,
      drinking: true,
      petFriendly: true,
      description: 'I have a 2BHK in Koregaon Park and looking for a female flatmate. I work in marketing and love to travel on weekends. Pet friendly household - I have a cat! Looking for someone who is clean, responsible, and friendly.',
      phone: '9876543221',
      userId: 'demo-flatmate-user-2',
      userEmail: 'priya.sharma@example.com',
      status: 'approved',
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      id: 'flatmate-3',
      name: 'Aman Singh',
      age: 28,
      gender: 'male',
      occupation: 'Data Analyst',
      preferredArea: 'Baner',
      budget: 12000,
      hasPlace: true,
      lookingFor: 'any',
      vegetarian: false,
      smoking: false,
      drinking: true,
      petFriendly: false,
      description: 'Chill and easy-going person. I have a place in Baner with an empty room. Working as a data analyst with flexible hours. Enjoy gaming, movies, and sports. Looking for a responsible flatmate who can share household responsibilities.',
      phone: '9876543222',
      userId: 'demo-flatmate-user-3',
      userEmail: 'aman.singh@example.com',
      status: 'approved',
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      id: 'flatmate-4',
      name: 'Sneha Patil',
      age: 23,
      gender: 'female',
      occupation: 'Graphic Designer',
      preferredArea: 'Viman Nagar',
      budget: 9000,
      hasPlace: false,
      lookingFor: 'female',
      vegetarian: true,
      smoking: false,
      drinking: false,
      petFriendly: true,
      description: 'Creative professional working as a graphic designer. Love art, music, and yoga. Looking for a female flatmate to share a place near my office in Viman Nagar. Vegetarian and pet lover. Would prefer someone who values a healthy lifestyle.',
      phone: '9876543223',
      userId: 'demo-flatmate-user-4',
      userEmail: 'sneha.patil@example.com',
      status: 'approved',
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      id: 'flatmate-5',
      name: 'Karan Desai',
      age: 25,
      gender: 'male',
      occupation: 'Business Analyst',
      preferredArea: 'Aundh',
      budget: 13000,
      hasPlace: false,
      lookingFor: 'male',
      vegetarian: false,
      smoking: false,
      drinking: true,
      petFriendly: false,
      description: 'Working professional looking for a flatmate in Aundh area. I work as a business analyst and enjoy fitness, traveling, and trying new restaurants. Looking for someone who is clean, organized, and has a positive attitude.',
      phone: '9876543224',
      userId: 'demo-flatmate-user-5',
      userEmail: 'karan.desai@example.com',
      status: 'approved',
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      id: 'flatmate-6',
      name: 'Ananya Iyer',
      age: 27,
      gender: 'female',
      occupation: 'HR Professional',
      preferredArea: 'Kharadi',
      budget: 11000,
      hasPlace: true,
      lookingFor: 'female',
      vegetarian: true,
      smoking: false,
      drinking: false,
      petFriendly: false,
      description: 'I have a comfortable 2BHK apartment in Kharadi. Working in HR and love cooking, reading, and meditation. Looking for a mature, responsible female flatmate. Vegetarian household. Prefer someone who maintains cleanliness and respects personal space.',
      phone: '9876543225',
      userId: 'demo-flatmate-user-6',
      userEmail: 'ananya.iyer@example.com',
      status: 'approved',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
    }
  ];
  
  localStorage.setItem('flatmateProfiles', JSON.stringify(mockFlatmates));
  console.log('Mock flatmate profiles seeded successfully!');
};
