// Seed data for demo purposes
export const seedMockData = () => {
  // Check if data already exists
  const existingListings = localStorage.getItem('propertyListings');
  if (existingListings && JSON.parse(existingListings).length > 0) {
    return; // Don't overwrite existing data
  }

  const mockListings = [
    {
      id: 'mock-1',
      category: 'pg',
      title: 'Comfortable Single Room PG in Koregaon Park',
      description: 'Fully furnished single room PG with all modern amenities. Perfect for working professionals. Located in the heart of Koregaon Park with easy access to offices and shopping areas.',
      propertyType: 'Single Room',
      area: 'Koregaon Park',
      address: 'Lane 5, North Main Road',
      price: 12000,
      amenities: ['WiFi', 'TV', 'AC', 'Fridge', 'Water'],
      lift: true,
      waterType: 'ro',
      ownerId: 'demo-owner-1',
      ownerName: 'Rahul Sharma',
      ownerEmail: 'rahul.sharma@example.com',
      ownerPhone: '9876543210',
      status: 'approved',
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-2',
      category: 'pg',
      title: 'Double Sharing PG Near Hinjewadi IT Park',
      description: 'Spacious double sharing accommodation with homely food and Wi-Fi. Just 10 minutes from Hinjewadi Phase 2.',
      propertyType: 'Double Sharing',
      area: 'Hinjewadi',
      address: 'Phase 2, Rajiv Gandhi IT Park Road',
      price: 8000,
      amenities: ['WiFi', 'TV', 'Fridge', 'Water'],
      lift: true,
      waterType: 'ro',
      ownerId: 'demo-owner-2',
      ownerName: 'Priya Patil',
      ownerEmail: 'priya.patil@example.com',
      ownerPhone: '9876543211',
      status: 'approved',
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-3',
      category: 'rent',
      title: 'Spacious 2BHK Apartment in Baner',
      description: 'Beautiful 2BHK flat with modern amenities, covered parking, and 24/7 security. Family-friendly society with park and gym.',
      propertyType: 'Apartment',
      area: 'Baner',
      address: 'Kumar Paradise, Baner Road',
      price: 25000,
      bedrooms: 2,
      bathrooms: 2,
      amenities: ['WiFi', 'AC', 'Water'],
      lift: true,
      waterType: 'both',
      ownerId: 'demo-owner-3',
      ownerName: 'Amit Kumar',
      ownerEmail: 'amit.kumar@example.com',
      ownerPhone: '9876543212',
      status: 'approved',
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-4',
      category: 'rent',
      title: 'Luxury 3BHK House in Aundh',
      description: 'Premium 3BHK independent house with private parking, garden, and terrace. Ideal for families looking for peaceful living.',
      propertyType: 'House',
      area: 'Aundh',
      address: 'Aundh Gaon, ITI Road',
      price: 45000,
      bedrooms: 3,
      bathrooms: 3,
      amenities: ['WiFi', 'TV', 'AC', 'Fridge', 'Water'],
      lift: false,
      waterType: 'ro',
      ownerId: 'demo-owner-4',
      ownerName: 'Sneha Desai',
      ownerEmail: 'sneha.desai@example.com',
      ownerPhone: '9876543213',
      status: 'approved',
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-5',
      category: 'sell',
      title: 'Modern 3BHK Apartment for Sale in Kharadi',
      description: 'Brand new 3BHK apartment with all modern amenities. Ready to move in. Great investment opportunity in rapidly developing area.',
      propertyType: 'Apartment',
      area: 'Kharadi',
      address: 'Eon Free Zone, Kharadi',
      price: 8500000,
      bedrooms: 3,
      bathrooms: 2,
      amenities: ['WiFi', 'AC', 'Water'],
      lift: true,
      waterType: 'ro',
      ownerId: 'demo-owner-5',
      ownerName: 'Vikram Singh',
      ownerEmail: 'vikram.singh@example.com',
      ownerPhone: '9876543214',
      status: 'approved',
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-6',
      category: 'sell',
      title: 'Premium Villa in Wakad',
      description: 'Luxurious 4BHK villa with private garden, swimming pool access, and club house. Perfect for large families.',
      propertyType: 'Villa',
      area: 'Wakad',
      address: 'Dange Chowk, Wakad',
      price: 15000000,
      bedrooms: 4,
      bathrooms: 4,
      amenities: ['WiFi', 'TV', 'AC', 'Fridge', 'Water'],
      lift: false,
      waterType: 'both',
      ownerId: 'demo-owner-6',
      ownerName: 'Anjali Mehta',
      ownerEmail: 'anjali.mehta@example.com',
      ownerPhone: '9876543215',
      status: 'approved',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-7',
      category: 'pg',
      title: 'Triple Sharing PG in Viman Nagar',
      description: 'Affordable triple sharing PG with homemade food included. Close to Phoenix Mall and IT companies.',
      propertyType: 'Triple Sharing',
      area: 'Viman Nagar',
      address: 'Near Airport Road',
      price: 6500,
      amenities: ['WiFi', 'Water'],
      lift: false,
      waterType: 'tap',
      ownerId: 'demo-owner-7',
      ownerName: 'Suresh Pawar',
      ownerEmail: 'suresh.pawar@example.com',
      ownerPhone: '9876543216',
      status: 'approved',
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&h=400&fit=crop'
    },
    {
      id: 'mock-8',
      category: 'rent',
      title: '1BHK Flat in Kothrud',
      description: 'Cozy 1BHK apartment perfect for bachelors or small families. Well connected to Karve Road and Law College Road.',
      propertyType: 'Apartment',
      area: 'Kothrud',
      address: 'Mayur Colony, Kothrud',
      price: 15000,
      bedrooms: 1,
      bathrooms: 1,
      amenities: ['WiFi', 'Water'],
      lift: true,
      waterType: 'tap',
      ownerId: 'demo-owner-8',
      ownerName: 'Deepak Joshi',
      ownerEmail: 'deepak.joshi@example.com',
      ownerPhone: '9876543217',
      status: 'approved',
      createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      aadhaarUploaded: true,
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop'
    }
  ];

  localStorage.setItem('propertyListings', JSON.stringify(mockListings));
  console.log('Mock data seeded successfully!');
};
